[pytest]
addopts = 
    --headed 
    --browser chromium 
    --base-url https://simplecommerce1nz5qlcr-formateur.functions.fnc.fr-par.scw.cloud
    --slowmo 0
    --tracing retain-on-failure
reruns = 2

# production 
# --screenshot

# or use --config-file=... to load a specific
# config file instead of trying to
# locate one of the implicit configuration files