[pytest]
addopts = 
    --headed 
    --browser chromium 
    --base-url https://simplecommerce1nz5qlcr-formateur.functions.fnc.fr-par.scw.cloud
    --slowmo 0
    --pdb

# visit https://playwright.dev/python/docs/test-runners#cli-arguments for argument list and definitions


